### PR TITLE
Akovarms patch 1

### PR DESCRIPTION
**Pull request by akovarms**
Adding Windows Processor Requirements details to Design site. Intentionally leaving this md out of the TOC as it will be accessed via a FWLink provided to our partners within licensing and other agreements.

### CODE REVIEW

**Comment by akovarms** [comment]
@joshbax-msft Josh could you review this pull request for me?

**Comment by joshbax-msft** [comment]
Hey Andy,

I’m not 100% on whether a topic not included in a TOC will be published. I’ll test this and get back to you.

Thanks,

Joshua

**Comment by akovarms** [comment]
Looks like there is already one with device-guard-and-credential-guard.md, which I've found you can get to as long as you provide the full URL https://docs.microsoft.com/en-us/windows-hardware/design/minimum/device-guard-and-credential-guard

**Comment by joshbax-msft** [comment]
Cool—sold! I believe this behavior has changed from time to time, so I wasn’t sure. I’ll have this published soon.

**Pull request merged**
