### PR TITLE
Update step-3-create-a-machine-pool.md

### PR DESCRIPTION
**Pull request by DOMARS**
@EliotSeattle - This is based on testing during the hackathon. Dev Team has reviewed.

@duncanmacmichael - This PR is for the HLK and is ready to go live.

### CODE REVIEW

**Comment by EliotSeattle** [comment]
Thanks, @DOMARS 
@duncanmacmichael you can merge at your leisure.

**Comment by duncanmacmichael** [comment]
Ah, since this is in the commercialization repo I don't have write access to do the merging. Sorry. @EliotSeattle do you know who does?

**Comment by EliotSeattle** [comment]
@dawnwood are you the gatekeeper?

**Comment by dawnwood** [comment]
@EliotSeattle done and done

**Pull request merged**
